{
	"??????????????????",
	"NOT HERE...",
	"FIGHTING DINOSAURS",
	"RIDING HIS BIKE",
	"THE MOON?",
	"REDIRECTING...",
	"UNABLE TO LOCATE",
	"LOCATION UNKNOWN",
	"WATCHING STAR TREK",
	"PLAYING MINECRAFT",
}